# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wash < Formula
  desc "WAsmcloud SHell - a comprehensive command-line tool for wasmCloud development"
  homepage "https://wasmcloud.com/"
  version "0.38.0"
  license "Apache-2.0"

  bottle do
    root_url "https://github.com/wasmCloud/homebrew-wasmcloud/releases/download/wash-0.38.0"
    sha256 cellar: :any_skip_relocation, ventura:      "ab411269cb687da5964f3357d5cf4734ffdf58fa31b2ecac51028498e8856518"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "307b6668d81ef4949b7ce544479c33fcab56602090ba8ad1aec899c8e2adc5a1"
  end

  on_macos do
    on_intel do
      url "https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v0.38.0/wash-x86_64-apple-darwin"
      sha256 "edec0fa45d5ed437322d2813714b5b268d3882bf5ba93f857eefef26f068037b"

      def install
        bin.install "wash-x86_64-apple-darwin" => "wash"
      end
    end
    on_arm do
      url "https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v0.38.0/wash-aarch64-apple-darwin"
      sha256 "c2d0443264d064c3f975809e945d19fb4180a3a1d21944e43ea261f7c3050450"

      def install
        bin.install "wash-aarch64-apple-darwin" => "wash"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v0.38.0/wash-x86_64-unknown-linux-musl"
        sha256 "8bba2463f4e121fdbbebc4046aabe1ade54aa3bd72ba70a57ad4b0e0e657bec2"

        def install
          bin.install "wash-x86_64-unknown-linux-musl" => "wash"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wasmCloud/wasmCloud/releases/download/wash-cli-v0.38.0/wash-aarch64-unknown-linux-musl"
        sha256 "bab4fad652eaa9bb1e890daa0478ec223aaf448fb72eb00e59014034a3bca345"

        def install
          bin.install "wash-aarch64-unknown-linux-musl" => "wash"
        end
      end
    end
  end

  test do
    system "#{bin}/wash", "-V"
  end
end
